server:
  port: 8091

spring:
  application:
    name: voting-system

  datasource:
    url: jdbc:mysql://localhost:3306/voting_system_db
    username: root
    password: 1434
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  auth:
    email: admin@example.com
    password: admin123
    role: ADMIN
